# Generated by Django 6.0 on 2026-03-28 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_imageninmueble_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='Agente',
            new_name='agente',
        ),
    ]
